sushisite/order/urls.py
from django.urls import path

from . import views

app_name = 'order'

urlpatterns = [
    path('order/all_orders/', views.all_orders, name='all_orders'),
    path('order/your_order/', views.your_order, name='your_order'),
    path('', views.order, name='order'),
]

sushisite/sushisite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('order/', include('order.urls')),
    path('admin/', admin.site.urls),
]

sushisite/order/models.py
from django.db import models

class MenuItem(models.Model):
    name = models.CharField(max_length=100)
    picture_path = models.CharField(max_length=200)

class Order(models.Model):
    date = models.DateTimeField(auto_now_add=True, blank=True)

class OrderItem(models.Model):
    order_id = models.ForeignKey(Order, on_delete=models.CASCADE)
    menu_item_id = models.ForeignKey(MenuItem, on_delete=models.CASCADE)

sushisite/order/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from . models import MenuItem, Order, OrderItem

def order(request):
    all_menu_items = reversed(MenuItem.objects.order_by('-id')[:])
    context = {'all_menu_items':all_menu_items,}
    return render(request, 'order/menu_items.html', context)

def your_order(request):
    new_order = Order()
    new_order.save() 

    menu_item_id = []
    item_counter = []
    for key, values in request.POST.lists():
        if key == 'menu_item_id':
            menu_item_id = values
        elif key == 'count':
            item_counter = values    
            
    for i in range(0, len(menu_item_id)):
        if item_counter[i] != '':
            # Item is ordered by user
            menu_item = MenuItem.objects.get(pk=menu_item_id[i])
            counter = int(item_counter[i])
            for j in range(0, counter):
                order_item = OrderItem(order_id=new_order, menu_item_id=menu_item)
                order_item.save()
    item_info = zip(menu_item_id, item_counter)
    context = {'item_info':item_info, 'i':i}
    return render(request, 'order/your_order.html', context)


def all_orders(request):
    order_list = Order.objects.all()
    order_item_lists = []

    for order in order_list:
        order_item_lists.append(OrderItem.objects.filter(order_id=order))
    orders = zip(order_list, order_item_lists)
    context = {'orders':orders}
    return render(request, 'order/all_orders.html', context)
    pass

sushisite/order/templates/order/all_orders.html
<center>
{% for order, order_item_list in orders %}
  <h4>Order number: {{ forloop.counter }}
  <h4>{{order.date}}</h4>
  {% for order_item in order_item_list %}
  <h4>{{order_item.menu_item_id}}</h5>
  {% endfor %}
  <br/>
{% endfor %}
</center>

sushisite/order/templates/order/menu_items.html
{% load static %}
{% comment %} {% include "header.html" %} {% endcomment %}
<link rel="stylesheet" type="text/css" href="{% static 'order/css/menu_items.css' %}" />
{% if all_menu_items %}
<a href="{% url 'order:all_orders' %}">weinsi</a>
<form id="menu" action="{% url 'order:your_order' %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Bestill" id="orderButton">
    {% for item in all_menu_items %}
      <div class="menuItem">
        <center>
        <img src="{% static "/order/images/"%}{{item.picture_path}}"/>
        <h4>{{ item.name }}</h4>
        <input type="number" min="0" name="count">
        <input type="hidden" value="{{item.id}}" name="menu_item_id">
        </center>
      </div>
    {% endfor %}
  </form>
{% else %}
  <p>No menu items</p>
{% endif %}

sushisite/order/templates/order/your_order.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'order/css/your_order.css' %}" />
{% if item_info %}
  <div id="your_order">
  {% for menu_item_id, item_counter in item_info %}
    {% if item_counter != '' %}
      <div class="orderItem">
        <center>
        <h4>Item id: {{menu_item_id}}</h4>
        <h4>Item counter: {{item_counter}}</h4>
        </center>
      </div>
    {% endif %}
  {% endfor %}
  </div>
{% else %}
  <p>Cant find order</p>
{% endif %}

sushisite/templates/header.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'header.css' %}"/>

<div id="header"> </div>

<div id="content"> 
</div>